apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.19.141.254:9090
    isDefault: true
    editable: true

  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://172.19.141.254:9100
    editable: true

  - name: MT5 Metrics
    type: prometheus
    access: proxy
    url: http://172.19.141.254:9090
    editable: true
    jsonData:
      queryTimeout: 60s
      httpMethod: POST